# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec3278038ead2959ab2339d5a9afa28c282b8d36c71b0e87104e5e89e1363139a184bbf5608c9ffba484883ef1472f1797d6345e27e2e5351107bf7bb77d5b53

test:
  secret_key_base: 9a13fd97a2341959552cea2241a37aad1943f39f70b3a6253998149558ccfa0dfc0c9f7407737b5221569244f81672878a536c58bba07528f19422794140fdb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
